framework:
    cache:
        app: cache.adapter.filesystem
        default_redis_provider: 'redis://localhost'
        
        pools:
            dashboard.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 300
